### ISSUE TITLE
Please create a "1.19.2" branch

### ISSUE THREAD

**Issue by hypevhs** [apace100/show-me-what-you-got#13]
Please create a "1.19.2" branch on the last commit to support that MC version: https://github.com/apace100/show-me-what-you-got/commit/18ebcf661fe0bc68ee33d1c4be935f24621ddec9. I would like to fix the crashes still occurring on this version.

This is the MC version that All of Fabric 6 uses.

**Comment by apace100** [comment]
Done! https://github.com/apace100/show-me-what-you-got/tree/1.19.2

I added the publishing workflow from more recent branches so I can release versions on there more easily. Feel free to send PRs!
