### ISSUE TITLE
Mixin plugin loads `Identifier`, breaking any Mixins into it

### ISSUE THREAD

**Issue by malte0811** [apace100/show-me-what-you-got#3]
[This](https://github.com/apace100/show-me-what-you-got/blob/9eb4af8219e43b56c31cfcdfa72a8cd526bd66a7/src/main/java/io/github/apace100/smwyg/compat/CalioPlugin.java#L38) line causes `ShowMeWhatYouGot` and indirectly `Identifier` to be loaded during Mixin preparation when an old version of calio is installed. This means that any Mixins into `Identifier` silently fail, causing malte0811/FerriteCore#59. You should never directly reference classes that can be transformed by Mixin in a mixin config plugin.

**Comment by apace100** [comment]
Thanks for the tip, I'll keep it in mind in the future.
For the new version I just uploaded (1.0.1), I removed the mixin plugin completely as the new version of Calio (1.5.0, for Minecraft 1.18.2) removes the necessity for this compatibility mixin.
